Kolya
Seva-Vaskin/texvide pull request #34
Opened 2024-11-28 08:35 UTC by buyolitsez

2024-12-02 17:46 UTC, buyolitsez commented
@Seva-Vaskin

2024-12-03 15:07 UTC, Seva-Vaskin requested changes

2024-12-03 15:07 UTC, Seva-Vaskin commented on config/nvim/ultisnips/tex/tex.snippets
> +snippet "([a-zA-Z])bar" "bar" riA
`bar`? maybe `til`?

2024-12-03 15:43 UTC, Seva-Vaskin approved these changes

2024-12-03 15:43 UTC, merged